### ISSUE TITLE
1.0.1t-1+deb8u2 causing compilation failures "error: ‘SSLv2_method’ redeclared as different kind of symbol"

### ISSUE THREAD

**Issue by russmac** [pyca/pyopenssl#492]
Reported this to Openssl and was advised issue is with Python.

https://github.com/openssl/openssl/issues/1190

On Debian 8.4, Linux ip-10-1-1-99 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

Since upgrading from 1.0.1k-3+deb8u5 ->  1.0.1t-1+deb8u2 I cannot install pip cryptography packages (irrespective of their version)

#### Reproduce
```
apt-get install --force-yes libssl-dev=1.0.1t-1+deb8u2 libssl1.0.0=1.0.1t-1+deb8u2 openssl=1.0.1t-1+deb8u2 build-essential python-pip python-dev libffi-dev
pip install cryptography
```
#### Workaround
```
apt-get install --force-yes libssl-dev=1.0.1k-3+deb8u5 libssl1.0.0=1.0.1k-3+deb8u5 openssl=1.0.1k-3+deb8u5
pip install cryptography
```

Force installing the previous version of openssl resolves the issue. Ive tried several version of pip cryptography from 1.0 to 1.4

It is easily reproduced with the packages / pip install cryptography.

I've debugged:
```
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 59: ordinal not in range(128)
```

And determined the encoding of my provisioner or shell has no effect and has always been set UTF8.

It looks like this may be the cause (caveat, I know zero C):
```
build/temp.linux-x86_64-2.7/_openssl.c:2096:15: error: ‘SSLv2_method’ redeclared as different kind of symbol
```

### full trace
```
building '_openssl' extension

creating build/temp.linux-x86_64-2.7/build

creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o

build/temp.linux-x86_64-2.7/_openssl.c:2096:15: error: ‘SSLv2_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_method)(void) = NULL;

               ^

In file included from build/temp.linux-x86_64-2.7/_openssl.c:523:0:

/usr/include/openssl/ssl.h:2021:19: note: previous declaration of ‘SSLv2_method’ was here

 const SSL_METHOD *SSLv2_method(void); /* SSLv2 */

                   ^

build/temp.linux-x86_64-2.7/_openssl.c:2097:15: error: ‘SSLv2_client_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_client_method)(void) = NULL;

               ^

In file included from build/temp.linux-x86_64-2.7/_openssl.c:523:0:

/usr/include/openssl/ssl.h:2023:19: note: previous declaration of ‘SSLv2_client_method’ was here

 const SSL_METHOD *SSLv2_client_method(void); /* SSLv2 */

                   ^

build/temp.linux-x86_64-2.7/_openssl.c:2098:15: error: ‘SSLv2_server_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_server_method)(void) = NULL;

               ^

In file included from build/temp.linux-x86_64-2.7/_openssl.c:523:0:

/usr/include/openssl/ssl.h:2022:19: note: previous declaration of ‘SSLv2_server_method’ was here

 const SSL_METHOD *SSLv2_server_method(void); /* SSLv2 */

                   ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Rolling back uninstall of cryptography
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-13wIIt/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1C0XrA-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-13wIIt/cryptography
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 59: ordinal not in range(128)
```

**Comment by alex** [comment]
pyca/cryptography was the right place to file this bug, can you update https://github.com/pyca/cryptography/issues/2973 with the right info.

**Comment by russmac** [comment]
Although its a failure in building cryptography the Openssl dev suggested it was the Python ssl extension with was the cause. I'm reopening the cryptography ticket.
